# Generated by Django 2.2.6 on 2019-10-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=120, verbose_name='id')),
                ('questions', models.CharField(max_length=500, verbose_name='question')),
                ('answers', models.CharField(max_length=1000, verbose_name='answer')),
            ],
        ),
    ]
